Repository Convergence-Project/step-service, pull requests merged in 2023-09, with the labels that each got.

#9 [Feat] : Scrap 엔티티 추가
  .github/pull_request_template.md
  src/main/java/com/example/stepbackend/aggregate/entity/Scrap.java
  src/main/resources/application-dev.yml
Labels: ✨feature

#10 [Feat, Rename] UserEntity, TokenEntity 구성
  build.gradle
  src/main/java/com/example/stepbackend/aggregate/entity/Token.java
  src/main/java/com/example/stepbackend/aggregate/entity/User.java
  src/main/java/com/example/stepbackend/aggregate/entity/enumType/Provider.java
  src/main/java/com/example/stepbackend/aggregate/entity/enumType/Role.java
  src/main/java/com/example/stepbackend/global/advice/Advice.java
  src/main/java/com/example/stepbackend/global/aop/Aop.java
  src/main/java/com/example/stepbackend/global/common/Common.java
  src/main/java/com/example/stepbackend/global/configuration/Configuration.java
  src/main/java/com/example/stepbackend/global/exception/Exception.java
  src/main/java/com/example/stepbackend/global/filter/Filter.java
  src/main/java/com/example/stepbackend/global/handler/Handler.java
  src/main/java/com/example/stepbackend/global/security/Security.java
  src/main/resources/application-dev.yml
Labels: ✨feature

#12 [Feat, Rename] SecurityConfig 등 관련 config 설정
  build.gradle
  src/main/java/com/example/stepbackend/StepBackendApplication.java
  src/main/java/com/example/stepbackend/aggregate/dto/user/CreateUserDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Token.java
  src/main/java/com/example/stepbackend/aggregate/entity/User.java
  src/main/java/com/example/stepbackend/aggregate/entity/enumType/Provider.java
  src/main/java/com/example/stepbackend/aggregate/entity/enumType/Role.java
  src/main/java/com/example/stepbackend/aggregate/entity/vo/UserVO.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/java/com/example/stepbackend/global/configuration/WebConfiguration.java
  src/main/java/com/example/stepbackend/global/configuration/WebMvcConfig.java
  src/main/java/com/example/stepbackend/global/exception/BadRequestException.java
  src/main/java/com/example/stepbackend/global/exception/Exception.java
  src/main/java/com/example/stepbackend/global/exception/InvalidParameterException.java
  src/main/java/com/example/stepbackend/global/exception/ResourceNotFoundException.java
  src/main/java/com/example/stepbackend/global/exception/UrlNullPointerException.java
  src/main/java/com/example/stepbackend/global/exception/UserNotFoundException.java
  src/main/java/com/example/stepbackend/global/exception/assertion/ExceptionAssert.java
  src/main/java/com/example/stepbackend/repository/TokenRepository.java
  src/main/java/com/example/stepbackend/repository/UserRepository.java
  src/main/java/com/example/stepbackend/service/CreateUserService.java
  src/main/resources/application.yml
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/UserMapper.xml
Labels: ✏️rename, ✨feature

#20 Feature/scrap 스크랩 기능 구현
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ScrapListDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/QuestionToMember.java
  src/main/java/com/example/stepbackend/aggregate/entity/Scrap.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/repository/QuestionRepository.java
  src/main/java/com/example/stepbackend/repository/ScrapRepository.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/resources/application-dev.yml
  src/main/resources/sql/data.sql
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
Labels: 🎯test, ✨feature

#22 Feature/security Security, Test코드 작성 완료
  build.gradle
  src/main/java/com/example/stepbackend/aggregate/dto/user/FindUserDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/user/UpdateUserDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Token.java
  src/main/java/com/example/stepbackend/aggregate/entity/User.java
  src/main/java/com/example/stepbackend/aggregate/entity/enumType/Role.java
  src/main/java/com/example/stepbackend/aggregate/entity/util/CustomCookie.java
  src/main/java/com/example/stepbackend/global/advice/Advice.java
  src/main/java/com/example/stepbackend/global/advice/AuthControllerAdvice.java
  src/main/java/com/example/stepbackend/global/common/Common.java
  src/main/java/com/example/stepbackend/global/common/response/api/ApiResponse.java
  src/main/java/com/example/stepbackend/global/common/response/error/ErrorResponse.java
  src/main/java/com/example/stepbackend/global/common/response/error/ErrorResponseBody.java
  src/main/java/com/example/stepbackend/global/configuration/AppPropertise.java
  src/main/java/com/example/stepbackend/global/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/example/stepbackend/global/exception/TokenNotFoundException.java
  src/main/java/com/example/stepbackend/global/exception/UserAuthenticationException.java
  src/main/java/com/example/stepbackend/global/exception/UserNotFoundException.java
  src/main/java/com/example/stepbackend/global/exception/assertion/ExceptionAssert.java
  src/main/java/com/example/stepbackend/global/filter/AuthenticationExceptionFilter.java
  src/main/java/com/example/stepbackend/global/filter/Filter.java
  src/main/java/com/example/stepbackend/global/filter/NullPointExceptionFilter.java
  src/main/java/com/example/stepbackend/global/filter/TokenAuthenticationFileter.java
  src/main/java/com/example/stepbackend/global/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/stepbackend/global/handler/CustomOAuth2FailHandler.java
  src/main/java/com/example/stepbackend/global/handler/Handler.java
  src/main/java/com/example/stepbackend/global/provider/Kakao.java
  src/main/java/com/example/stepbackend/global/provider/OAuth2UserInfo.java
  src/main/java/com/example/stepbackend/global/provider/OAuth2UserInfoFactory.java
  src/main/java/com/example/stepbackend/global/security/controller/AuthController.java
  src/main/java/com/example/stepbackend/global/security/dto/AuthResponse.java
  src/main/java/com/example/stepbackend/global/security/dto/AuthResponseBody.java
  src/main/java/com/example/stepbackend/global/security/dto/RefreshAccessTokenDTO.java
  src/main/java/com/example/stepbackend/global/security/service/CustomOAuth2UserService.java
  src/main/java/com/example/stepbackend/global/security/service/CustomTokenService.java
  src/main/java/com/example/stepbackend/global/security/service/CustomUserDetailService.java
  src/main/java/com/example/stepbackend/global/security/service/IssueTokenService.java
  src/main/java/com/example/stepbackend/global/security/service/RequestUser.java
  src/main/java/com/example/stepbackend/global/security/service/RequestUserService.java
  src/main/java/com/example/stepbackend/global/security/service/RestAuthenticationEntryPoint.java
  src/main/java/com/example/stepbackend/global/security/token/UserPrincipal.java
  src/main/java/com/example/stepbackend/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/example/stepbackend/repository/TokenRepository.java
  src/main/java/com/example/stepbackend/repository/UserMapper.java
  src/main/java/com/example/stepbackend/service/FindUserService.java
  src/main/java/com/example/stepbackend/service/UpdateUserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/mapper/UserMapper.xml
  src/test/java/com/example/stepbackend/global/security/advice/AuthControllerAdviceUnitTest.java
  src/test/java/com/example/stepbackend/global/security/service/CustomTokenServiceTest.java
  src/test/java/com/example/stepbackend/global/security/service/IssueTokenServiceTest.java
  src/test/java/com/example/stepbackend/service/CreateUserServiceTest.java
  src/test/java/com/example/stepbackend/service/FindUserServiceTest.java
Labels: 🎯test, ✨feature

#26 [Feat] SecurityConfig 설정 완료
  build.gradle
  src/main/java/com/example/stepbackend/global/advice/AuthControllerAdvice.java
  src/main/java/com/example/stepbackend/global/configuration/AppProperties.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/java/com/example/stepbackend/global/filter/TokenAuthenticationFileter.java
  src/main/java/com/example/stepbackend/global/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/stepbackend/global/handler/CustomOAuth2FailHandler.java
  src/main/java/com/example/stepbackend/global/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/example/stepbackend/repository/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/resources/application-dev.yml
  src/test/java/com/example/stepbackend/global/security/service/CustomTokenServiceTest.java
Labels: ✅fix, ✨feature

#25 [Feat] : 스크랩 및 문제집 관련 수정사항
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/CreateScrapDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/CreateWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Scrap.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/repository/ScrapRepository.java
  src/main/java/com/example/stepbackend/repository/WorkBookRepository.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: 🐞bugfix, ✨feature

#27 [Feat, Test] @CurrentUser 어노테이션
  src/main/java/com/example/stepbackend/global/common/annotation/CurrentUser.java
Labels: 🛠️refactor, 🎯test, ✨feature

#31 Feature/workbook 삭제 엔티티 복구
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/CreateWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/SelectedItemsDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/QuestionToMember.java
  src/main/java/com/example/stepbackend/controller/WorkBookController.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/sql/data.sql
Labels: ✅fix

#33 [Feat] : 나만의 문제집 공유 기능
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/IsSharedWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/repository/WorkBookRepository.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/sql/data.sql
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: 🎯test, ✨feature

#44 Feature/create workbook 문제집 및 스크랩 리팩토링
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/CreateWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/CreateWorkBookRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/controller/WorkBookController.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: 🛠️refactor, 🎯test

#48 Hotfix/workbook 문제집 테스트 코드 수정
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/CreateScrapDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/QuestionToMember.java
  src/main/java/com/example/stepbackend/aggregate/entity/Scrap.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/resources/templates/scrap/myScrapPage.html
  src/main/resources/templates/testPage.html
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: ✅fix, 🎯test

#42 Feature/common
  src/main/java/com/example/stepbackend/controller/MainController.java
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/resources/application-dev.yml
  src/main/resources/static/assets/img/icon_question_check.png
  src/main/resources/static/assets/img/step_logo.svg
  src/main/resources/static/sql/data.sql
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/main.html
  src/main/resources/templates/questions/question.html
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: ✨feature

#51 [Feat] : header 및 footer 변경
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header.html
Labels: 🐞bugfix, 🎨design

#52 Feature/question 문제 조회 페이지 추가
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/repository/QuestionByMemberRepository.java
  src/main/java/com/example/stepbackend/repository/QuestionRepository.java
  src/main/java/com/example/stepbackend/service/QuestionService.java
  src/main/resources/templates/questions/question.html
Labels: 🎨design, ✨feature

#54 [Feat] : 스크랩 문제 확인 페이지 구현
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapAndMemberDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapByMemberDTO.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/repository/QuestionByMemberRepository.java
  src/main/java/com/example/stepbackend/repository/QuestionRepository.java
  src/main/java/com/example/stepbackend/repository/ScrapRepository.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/resources/sql/data.sql
  src/main/resources/templates/common/header.html
  src/main/resources/templates/scrap/myScrapPage.html
  src/main/resources/templates/scrap/scrapDetail.html
  src/main/resources/templates/testPage.html
Labels: ✨feature

#56 [Refactor] : 공용 헤더 수정
  src/main/resources/templates/common/header.html
Labels: 🛠️refactor

#57 Feature/question 문제 풀이
  src/main/java/com/example/stepbackend/aggregate/dto/question/ReqQuestionByMemberDTO.java
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/repository/QuestionRepository.java
  src/main/java/com/example/stepbackend/service/QuestionService.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
  src/test/java/com/example/stepbackend/service/QuestionServiceTest.java
Labels: 🎨design, 🎯test, ✨feature

#59 [Feat] : 문제집 생성 및 문제집 조회 페이지 생성
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapAndMemberDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/CreateWorkBookRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/ReadWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/controller/WorkBookController.java
  src/main/java/com/example/stepbackend/repository/QuestionByMemberRepository.java
  src/main/java/com/example/stepbackend/repository/WorkBookRepository.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/scrap/myScrapPage.html
  src/main/resources/templates/scrap/scrapDetail.html
  src/main/resources/templates/workbook/myWorkbookPage.html
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: ✨feature

#68 [Refactor, Rename] : workBook entity isShared 필드 삭제
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/ReadWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Board.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/repository/BoardRepository.java
  src/main/java/com/example/stepbackend/service/BoardService.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/test/java/com/example/stepbackend/service/BoardServiceTest.java
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: 🛠️refactor

#73 [Refactor] : 스크랩 상세 페이지 수정
  src/main/resources/templates/common/header.html
  src/main/resources/templates/scrap/scrapDetail.html
Labels: 🛠️refactor

#74 [Feat, Test] User,Security 관련 test 추가
  src/main/java/com/example/stepbackend/global/security/controller/AuthController.java
  src/main/java/com/example/stepbackend/global/security/service/CustomTokenService.java
  src/main/java/com/example/stepbackend/service/CreateUserService.java
  src/main/java/com/example/stepbackend/service/UpdateUserService.java
  src/main/resources/application-dev.yml
  src/test/java/com/example/stepbackend/global/filter/TokenAuthenticationFilterTest.java
  src/test/java/com/example/stepbackend/global/security/advice/AuthControllerAdviceUnitTest.java
  src/test/java/com/example/stepbackend/global/security/controller/AuthControllerTest.java
  src/test/java/com/example/stepbackend/global/security/service/CustomTokenServiceTest.java
Labels: 🎯test

#76 [Feat] : 문제집 리그 게시판 수정 구현
  src/main/java/com/example/stepbackend/aggregate/dto/board/UpdateBoardRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/UpdateBoardResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Board.java
  src/main/java/com/example/stepbackend/controller/BoardController.java
  src/main/java/com/example/stepbackend/repository/BoardRepository.java
  src/main/java/com/example/stepbackend/service/BoardService.java
  src/main/resources/templates/board/board.html
  src/test/java/com/example/stepbackend/service/BoardServiceTest.java
Labels: 🎯test, ✨feature

#77 Feature/question 문제 풀이, 정답보기 디버깅
  src/main/java/com/example/stepbackend/aggregate/entity/QuestionByMember.java
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/service/QuestionService.java
  src/main/resources/static/assets/img/o.png
  src/main/resources/static/assets/img/x.png
  src/main/resources/templates/questions/grading-modal.html
  src/main/resources/templates/questions/modal.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
Labels: 🐞bugfix, ✨feature

#79 [Feat] : 문제집 리그 삭제 및 좋아요 구현
  src/main/java/com/example/stepbackend/aggregate/dto/Heart/PostHeartRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/Heart/PostHeartResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/DeleteBoardDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/ReadBoardPageDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Board.java
  src/main/java/com/example/stepbackend/aggregate/entity/Heart.java
  src/main/java/com/example/stepbackend/controller/BoardController.java
  src/main/java/com/example/stepbackend/repository/HeartRepository.java
  src/main/java/com/example/stepbackend/service/BoardService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/board/board.html
  src/test/java/com/example/stepbackend/service/BoardServiceTest.java
Labels: 🎯test, ✨feature

#85 Feature/borad solve 문제집 풀기 구현
  src/main/java/com/example/stepbackend/aggregate/dto/board/ReadBoardQuestionResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/ReadScrapBoardDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/SolveQuestionRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/SolveQuestionResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/CreateScrapDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Board.java
  src/main/java/com/example/stepbackend/aggregate/entity/QuestionByMember.java
  src/main/java/com/example/stepbackend/aggregate/entity/Scrap.java
  src/main/java/com/example/stepbackend/controller/BoardController.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/repository/BoardRepository.java
  src/main/java/com/example/stepbackend/repository/QuestionByMemberRepository.java
  src/main/java/com/example/stepbackend/repository/QuestionRepository.java
  src/main/java/com/example/stepbackend/repository/ScrapRepository.java
  src/main/java/com/example/stepbackend/service/BoardService.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/resources/static/assets/img/testPaper.png
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/question.html
  src/main/resources/templates/board/result-modal.html
  src/test/java/com/example/stepbackend/service/BoardServiceTest.java
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
Labels: 🎯test, ✨feature

#92 Feature/workbook solve 나만의 문제집 페이지 var -> const 변경
  src/main/resources/templates/workbook/myWorkbookPage.html
Labels: 🛠️refactor

#94 Feature/question 정답 보기
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/resources/static/assets/js/generateQuestion.js
  src/main/resources/static/assets/js/wookbook.js
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
Labels: 🐞bugfix, 🛠️refactor

#96 [Refactor] : 스크랩 페이지 삭제 구현
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/CancelScrapRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/CancelScrapResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapListDTO.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/repository/ScrapRepository.java
  src/main/java/com/example/stepbackend/service/ScrapService.java
  src/main/resources/templates/board/board.html
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/scrap/myScrapPage.html
  src/test/java/com/example/stepbackend/service/ScrapServiceTest.java
Labels: 🛠️refactor

#101 [Feat] : 문제집 리그에서 문제 풀고 나만의 문제집으로 이동 구현
  src/main/java/com/example/stepbackend/aggregate/dto/board/CreateBoardRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/CreateSolveAfterRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/board/CreateSolveAfterResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/ReadWorkBookDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/WorkBook.java
  src/main/java/com/example/stepbackend/controller/BoardController.java
  src/main/java/com/example/stepbackend/service/BoardService.java
  src/main/resources/templates/board/question.html
  src/main/resources/templates/scrap/myScrapPage.html
  src/main/resources/templates/scrap/scrapDetail.html
  src/main/resources/templates/workbook/myWorkbookPage.html
  src/test/java/com/example/stepbackend/service/BoardServiceTest.java
Labels: 🗑️remove, ✨feature

#99 [Feat] : 문제 해설 보기
  src/main/java/com/example/stepbackend/aggregate/dto/question/QuestionDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/question/ResQuestionDTO.java
  src/main/java/com/example/stepbackend/aggregate/entity/Question.java
  src/main/java/com/example/stepbackend/aggregate/entity/Report.java
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/controller/ReportController.java
  src/main/java/com/example/stepbackend/service/QuestionService.java
  src/main/java/com/example/stepbackend/service/ReportService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
  src/test/java/com/example/stepbackend/controller/QuestionControllerTest.java
  src/test/java/com/example/stepbackend/service/QuestionServiceTest.java
Labels: 🎨design, ✨feature

#103 [Feat] : 문제집 pdf 구현 및 공유 받은 문제집 공유 안되는 기능 구현
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/FindWorkBookResponse.java
  src/main/java/com/example/stepbackend/controller/WorkBookController.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/templates/board/question.html
  src/main/resources/templates/workbook/myWorkbookPage.html
Labels: 🛠️refactor, ✨feature

#106 [Feature] User-Login
  Test Results - 9project_[test].html
  build.gradle
  src/main/java/com/example/stepbackend/aggregate/dto/user/SignUpDTO.java
  src/main/java/com/example/stepbackend/controller/MainController.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/java/com/example/stepbackend/global/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/example/stepbackend/global/provider/Kakao.java
  src/main/java/com/example/stepbackend/global/provider/OAuth2UserInfo.java
  src/main/java/com/example/stepbackend/global/security/controller/AuthController.java
  src/main/java/com/example/stepbackend/global/security/service/CustomOAuth2UserService.java
  src/main/java/com/example/stepbackend/global/security/token/UserPrincipal.java
  src/main/resources/application-dev.yml
  src/main/resources/static/assets/img/kakao_login_large_narrow.png
  src/main/resources/templates/common/header.html
  src/main/resources/templates/oauth/mypage.html
  src/main/resources/templates/oauth/signin.html
  src/main/resources/templates/oauth/signup.html
  src/test/java/com/example/stepbackend/service/FindUserServiceTest.java
Labels: ✨feature

#108 Refactor/workbook 문제집 필터링 추가
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/FilterWorkBookRequestDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/FilterWorkBookResponseDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/FindWorkBookResponse.java
  src/main/java/com/example/stepbackend/controller/ScrapController.java
  src/main/java/com/example/stepbackend/controller/WorkBookController.java
  src/main/java/com/example/stepbackend/repository/WorkBookRepository.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/workbook/myWorkbookPage.html
  src/test/java/com/example/stepbackend/service/WorkbookServiceTest.java
Labels: 🛠️refactor, ✨feature

#109 [Feat] : 로그인 된 회원 정보 가져오기(문제)
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/main.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
Labels: 🛠️refactor, ✨feature

#112 Feature/profile user
  src/main/java/com/example/stepbackend/controller/MainController.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/java/com/example/stepbackend/global/security/token/UserPrincipal.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/oauth/mypage.html
  src/main/resources/templates/oauth/signin.html
  src/test/java/com/example/stepbackend/global/filter/TokenAuthenticationFilterTest.java
  src/test/java/com/example/stepbackend/global/security/service/IssueTokenServiceTest.java
Labels: 🎨design, ✨feature

#114 [Feat] User 로그인 유무에 따른 버튼
  build.gradle
  src/main/java/com/example/stepbackend/controller/MainController.java
  src/main/java/com/example/stepbackend/global/configuration/SecurityConfig.java
  src/main/resources/templates/common/header.html
  src/main/resources/templates/oauth/mypage.html
Labels: 🐞bugfix, 🎨design, ✨feature

#117 [Feat] : 통계 기능(나의 학습 현황)
  src/main/java/com/example/stepbackend/aggregate/dto/statistics/ReadStatisticsDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/statistics/TodayStatisticsDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/statistics/TotalStatisticsDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/statistics/WeekStatisticsDTO.java
  src/main/java/com/example/stepbackend/controller/StatisticsController.java
  src/main/java/com/example/stepbackend/repository/StatisticsMapper.java
  src/main/java/com/example/stepbackend/service/StatisticsService.java
  src/main/resources/mapper/StatisticsMapper.xml
  src/main/resources/templates/common/header.html
  src/main/resources/templates/statistics/myStatisticsPage.html
Labels: 🎨design, ✨feature

#119 Feature/question 문제 풀이에서 스크랩 중복 요청 되지 않게 변경
  src/main/resources/templates/questions/question.html
Labels: 🐞bugfix

#120 Featue/statistics 다크모드 CSS제거, 문제 풀이 수 0일 경우, 정답률 '-'로 표시
  src/main/resources/templates/board/result-modal.html
  src/main/resources/templates/main.html
  src/main/resources/templates/questions/grading-modal.html
  src/main/resources/templates/questions/modal.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/questions/result-modal.html
  src/main/resources/templates/scrap/myScrapPage.html
  src/main/resources/templates/statistics/myStatisticsPage.html
Labels: 🎨design

#122 [BugFix] : 문제 풀고 스크랩 안되는 이슈, 정오답 표기 오류 이슈 해결
  src/main/java/com/example/stepbackend/aggregate/dto/board/ReadBoardPageDTO.java
  src/main/java/com/example/stepbackend/aggregate/dto/scrap/ReadScrapListDTO.java
  src/main/java/com/example/stepbackend/controller/BoardController.java
  src/main/resources/templates/board/board.html
  src/main/resources/templates/board/question.html
  src/main/resources/templates/scrap/myScrapPage.html
Labels: 🐞bugfix, 🛠️refactor

#124 Feature/question 문제 pdf, 문제 보기 잘리는 현상
  src/main/java/com/example/stepbackend/controller/QuestionController.java
  src/main/java/com/example/stepbackend/service/QuestionService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/common/header.html
  src/main/resources/templates/questions/question.html
  src/main/resources/templates/statistics/myStatisticsPage.html
Labels: 🐞bugfix

#127 [Refactor] : 문제 유형 추가 및 라벨 추가, 라벨이 잘리면 수직으로 쌓이게 변경
  src/main/java/com/example/stepbackend/aggregate/dto/workbook/FilterWorkBookRequestDTO.java
  src/main/java/com/example/stepbackend/service/WorkbookService.java
  src/main/resources/templates/workbook/myWorkbookPage.html
Labels: ✅fix, 🛠️refactor

#129 [BugFix] : 라벨 많아질 때, 수정 삭제 버튼 안보이는 이슈 해결 및 라벨 추가
  src/main/resources/templates/board/board.html
Labels: 🐞bugfix, ✅fix, 🛠️refactor
